version: '3.8'

services:
  prompt-shirts:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    volumes:
      - ./public/images:/app/public/images:ro 